/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;
import org.example.service.VentaService;
import org.example.service.ReporteService;
import org.example.model.Venta;
import org.springframework.beans.factory.annotation.Autowired;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.URI;
import java.time.LocalDate;
import java.util.List;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import org.example.util.JsonUtil;





/**
 *
 * @author moral
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    @Autowired
    private VentaService ventaService;
    
    @Autowired
    private ReporteService reporteService;
    
    public Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opcionesCombo = new javax.swing.JComboBox<>();
        metodosCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadosTable = new javax.swing.JTable();
        btnMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Punto de venta TaCarbon - Estadisticas y Reportes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("ESTADISTICAS Y REPORTES");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel2.setText("Elige una operación");

        opcionesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas", "Estadísticas" }));
        opcionesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesComboActionPerformed(evt);
            }
        });

        metodosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodosComboActionPerformed(evt);
            }
        });

        resultadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultadosTable);

        btnMenuPrincipal.setBackground(new java.awt.Color(220, 220, 220));
        btnMenuPrincipal.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        btnMenuPrincipal.setPreferredSize(new java.awt.Dimension(150, 50));
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opcionesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metodosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesComboActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) opcionesCombo.getSelectedItem();
        metodosCombo.removeAllItems();

    if ("Ventas".equals(seleccion)) {
        metodosCombo.addItem("Obtener Todas las Ventas");
        metodosCombo.addItem("Obtener Venta por ID");
        metodosCombo.addItem("Eliminar Venta");
    } else if ("Estadísticas".equals(seleccion)) {
        metodosCombo.addItem("Obtener Ventas por Fecha");
        metodosCombo.addItem("Obtener Productos Más Vendidos");
        metodosCombo.addItem("Obtener Ingresos por Período");
    }
    }//GEN-LAST:event_opcionesComboActionPerformed

    private void metodosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodosComboActionPerformed
    String seleccion = (String) opcionesCombo.getSelectedItem();
    String metodoSeleccionado = (String) metodosCombo.getSelectedItem();
    
    if (seleccion == null || metodoSeleccionado == null) return;
    
    DefaultTableModel tableModel = new DefaultTableModel();
    resultadosTable.setModel(tableModel);

    HttpClient client = HttpClient.newHttpClient();
    ObjectMapper mapper = JsonUtil.getObjectMapper(); // Use ObjectMapper with JavaTimeModule
    
    try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/tacarbon_db?createDatabaseIfNotExist=true", "root", "m1o3r5a7")) 
    
    {
        if ("Ventas".equals(seleccion)) {
            if ("Obtener Todas las Ventas".equals(metodoSeleccionado)) {
                HttpRequest request = HttpRequest.newBuilder()
                        .uri(URI.create("http://localhost:8080/api/ventas"))
                        .GET()
                        .build();

                HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

                if (response.statusCode() == 200) {
                    List<Venta> ventas = mapper.readValue(response.body(), new TypeReference<List<Venta>>() {});

                    tableModel.addColumn("ID");
                    tableModel.addColumn("Fecha");
                    tableModel.addColumn("Total");

                    for (Venta v : ventas) {
                        tableModel.addRow(new Object[]{v.getId(), v.getFecha(), v.getTotal()});
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al obtener ventas: " + response.body());
                }
            } else if ("Obtener Venta por ID".equals(metodoSeleccionado)) {
                String id = JOptionPane.showInputDialog("Ingrese el ID de la venta:");
                try {
                    Long ventaId = Long.parseLong(id);

                    HttpRequest request = HttpRequest.newBuilder()
                            .uri(URI.create("http://localhost:8080/api/ventas/" + ventaId))
                            .GET()
                            .build();

                    HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

                    if (response.statusCode() == 200) {
                        Venta venta = mapper.readValue(response.body(), Venta.class);

                        tableModel.addColumn("ID");
                        tableModel.addColumn("Fecha");
                        tableModel.addColumn("Total");
                        tableModel.addRow(new Object[]{venta.getId(), venta.getFecha(), venta.getTotal()});
                    } else {
                        JOptionPane.showMessageDialog(this, "Venta no encontrada.");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "ID inválido.");
                }
            } else if ("Eliminar Venta".equals(metodoSeleccionado)) {
                String id = JOptionPane.showInputDialog("Ingrese el ID de la venta a eliminar:");
                try {
                    Long ventaId = Long.parseLong(id);

                    HttpRequest request = HttpRequest.newBuilder()
                            .uri(URI.create("http://localhost:8080/api/ventas/" + ventaId))
                            .DELETE()
                            .build();

                    HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

                    if (response.statusCode() == 204) {
                        JOptionPane.showMessageDialog(this, "Venta eliminada exitosamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al eliminar venta.");
                    }
                }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido.");
                }   
            }
            } else if ("Estadísticas".equals(seleccion)) {
            if ("Obtener Ventas por Fecha".equals(metodoSeleccionado)) {
                String fechaStr = JOptionPane.showInputDialog("Ingrese la fecha (YYYY-MM-DD):");
                LocalDate fecha = LocalDate.parse(fechaStr);

                String sql = "SELECT id, fecha, total FROM venta WHERE fecha BETWEEN ? AND ?";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setTimestamp(1, Timestamp.valueOf(fecha.atStartOfDay()));
                    stmt.setTimestamp(2, Timestamp.valueOf(fecha.plusDays(1).atStartOfDay()));
                    
                    try (ResultSet rs = stmt.executeQuery()) {
                        tableModel.addColumn("ID");
                        tableModel.addColumn("Fecha");
                        tableModel.addColumn("Total");

                        while (rs.next()) {
                            tableModel.addRow(new Object[]{
                                rs.getLong("id"), 
                                rs.getTimestamp("fecha").toLocalDateTime(), // Ensure format consistency
                                rs.getDouble("total")
                            });
                        }
                    }
                }
            } else if ("Obtener Productos Más Vendidos".equals(metodoSeleccionado)) {
                String sql = """
                    SELECT p.nombre, SUM(d.cantidad) AS total_vendido
                    FROM detalle_venta d
                    JOIN productos p ON d.producto_id = p.id
                    GROUP BY p.nombre
                    ORDER BY total_vendido DESC
                """;

                try (Statement stmt = conn.createStatement();
                     ResultSet rs = stmt.executeQuery(sql)) {

                    tableModel.addColumn("Producto");
                    tableModel.addColumn("Cantidad Vendida");

                    while (rs.next()) {
                        tableModel.addRow(new Object[]{
                            rs.getString("nombre"),
                            rs.getInt("total_vendido")
                        });
                    }
                }
            } else if ("Obtener Ingresos por Período".equals(metodoSeleccionado)) {
                String inicio = JOptionPane.showInputDialog("Ingrese la fecha de inicio (YYYY-MM-DD):");
                String fin = JOptionPane.showInputDialog("Ingrese la fecha de fin (YYYY-MM-DD):");

                LocalDate fechaInicio = LocalDate.parse(inicio);
                LocalDate fechaFin = LocalDate.parse(fin);

                String sql = "SELECT SUM(total) AS total_ingresos FROM venta WHERE fecha BETWEEN ? AND ? AND estado != 'Eliminada'";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setTimestamp(1, Timestamp.valueOf(fechaInicio.atStartOfDay()));
                    stmt.setTimestamp(2, Timestamp.valueOf(fechaFin.plusDays(1).atStartOfDay()));

                    try (ResultSet rs = stmt.executeQuery()) {
                        tableModel.addColumn("Total Ingresos");
                        if (rs.next()) {
                            tableModel.addRow(new Object[]{rs.getDouble("total_ingresos")});
                        }
                    }
                }
            }
        }
     } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener estadísticas: " + e.getMessage());
     } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
     }

     tableModel.fireTableDataChanged(); 
        
    }//GEN-LAST:event_metodosComboActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    
        // Open the MainPOSWindow
        MainPOSWindow mainWindow = new MainPOSWindow();
        mainWindow.setVisible(true);  // Show the MainPOSWindow
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> metodosCombo;
    private javax.swing.JComboBox<String> opcionesCombo;
    private javax.swing.JTable resultadosTable;
    // End of variables declaration//GEN-END:variables
}
