/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

import org.example.service.UsuarioService;

/**
 *
 * @author moral
 */
public class MainPOSWindow extends javax.swing.JFrame {
    private UsuarioService usuarioService; //Declare the service
    // Lista estática para rastrear todas las instancias abiertas
    private static final List<MainPOSWindow> instances = new ArrayList<>();

    /**
     * Creates new form MainPOSWindow
     */
    public MainPOSWindow() {
        instances.add(this); // Agrega la nueva instancia a la lista
        initComponents();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
        
        // Agregamos listener personalizado
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (instances.size() > 1) {
                    // Si hay más de una instancia, solo la cierra
                    dispose();
                } else {
                    // Si es la única ventana abierta, pedir confirmación para salir
                    int confirm = JOptionPane.showConfirmDialog(
                            MainPOSWindow.this,
                            "Si cierras esta ventana se cerrará el programa. ¿Estás seguro que deseas continuar?",
                            "Confirmar salida",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                    );
                    if (confirm == JOptionPane.YES_OPTION) {
                        System.exit(0); // Cierra toda la app
                    }
                    // Si elige "No", no hace nada (ventana sigue abierta)
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
                // Quita la instancia cerrada de la lista
                instances.remove(MainPOSWindow.this);
            }
        });

        setVisible(true); // Mostrar ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarVenta = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnPantallaCocina = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnConfiguracionDeServidor = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Punto de Venta TaCarbon - Menu Principal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        btnRegistrarVenta.setBackground(new java.awt.Color(205, 205, 205));
        btnRegistrarVenta.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVenta);

        btnInventario.setBackground(new java.awt.Color(205, 205, 205));
        btnInventario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnInventario.setText("Productos");
        btnInventario.setBorder(new javax.swing.border.MatteBorder(null));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario);

        btnPantallaCocina.setBackground(new java.awt.Color(205, 205, 205));
        btnPantallaCocina.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnPantallaCocina.setText("Pantalla Cocina");
        btnPantallaCocina.setBorder(new javax.swing.border.MatteBorder(null));
        btnPantallaCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantallaCocinaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPantallaCocina);

        btnUsuarios.setBackground(new java.awt.Color(205, 205, 205));
        btnUsuarios.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnUsuarios.setText("<html><center>Administrar<br>Usuarios</center></html>");
        btnUsuarios.setBorder(new javax.swing.border.MatteBorder(null));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios);

        btnEstadisticas.setBackground(new java.awt.Color(205, 205, 205));
        btnEstadisticas.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.setBorder(new javax.swing.border.MatteBorder(null));
        btnEstadisticas.setPreferredSize(new java.awt.Dimension(800, 500));
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadisticas);

        btnConfiguracionDeServidor.setBackground(new java.awt.Color(204, 204, 204));
        btnConfiguracionDeServidor.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnConfiguracionDeServidor.setText("<html><center>Configuración<br>del Servidor</center></html>");
        btnConfiguracionDeServidor.setBorder(new javax.swing.border.MatteBorder(null));
        btnConfiguracionDeServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionDeServidorActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfiguracionDeServidor);

        btnCerrarSesion.setBackground(new java.awt.Color(155, 155, 155));
        btnCerrarSesion.setFont(new java.awt.Font("Yu Gothic Medium", 3, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.MatteBorder(null));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPantallaCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantallaCocinaActionPerformed
        // TODO add your handling code here:
        
        new PantallaCocina().setVisible(true);
        
    }//GEN-LAST:event_btnPantallaCocinaActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
        
        new Estadisticas().setVisible(true);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        // Confirmar antes de cerrar sesión
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro que deseas cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Cerrar todas las instancias de MainPOSWindow
            for (MainPOSWindow ventana : new ArrayList<>(MainPOSWindow.instances)) {
                ventana.dispose();
            }

            // Mostrar login
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        
        RegistroVentaForm ventaForm = new RegistroVentaForm();
        ventaForm.setVisible(true);
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        
        new RegistroProductosForm().setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        
        new RegistroUsuarioForm().setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnConfiguracionDeServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionDeServidorActionPerformed
        new ConfiguracionIPForm().setVisible(true);
    }//GEN-LAST:event_btnConfiguracionDeServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPOSWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPOSWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPOSWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPOSWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPOSWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfiguracionDeServidor;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPantallaCocina;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
