/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import org.springframework.beans.factory.annotation.Autowired;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.event.TableModelListener;
import javax.swing.event.TableModelEvent;
import org.example.service.VentaService; // Adjust if it's in another package
import org.example.repository.ProductoRepository;
import javax.swing.JOptionPane; // For displaying messages in UI
import javax.swing.table.DefaultTableModel; // To handle JTable data
import java.io.OutputStream; // To send data in HTTP request
import java.net.HttpURLConnection; // To handle HTTP connection
import java.net.URL; // To define API endpoint
import java.util.ArrayList; // For list operations
import java.util.List; // For handling list of objects
import com.google.gson.Gson; // For JSON serialization
import java.util.Collections;
import java.util.HashMap; // For the sale data map
import java.util.Map; // For the sale data map
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author moral
 */
public class RegistroVentaForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVentaForm
     */
    private VentaService ventaService; // Declare the service

     @Autowired
private ProductoRepository productoRepository;
     
     

    public RegistroVentaForm() {
        
        initComponents();
        ventaService = new VentaService(); // Initialize the service
        subordenes.add(1); // Ensure Suborden 1 is always in the list
        currentSuborden = 1; // Set it as the active Suborden
        cargarProductos();
        
    try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tacarbon_db", "root", "m1o3r5a7");
    ventaService = new VentaService();
    } catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
    }
        
}
    
    
    private List<Integer> subordenes = new ArrayList<>();
    private int currentSuborden = 1; // Keeps track of the current suborden


            private void cargarProductos() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tacarbon_db", "root", "m1o3r5a7");
        String sql = "SELECT nombre FROM productos";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        cbxProductos.removeAllItems(); // Limpiar antes de agregar

        while (rs.next()) {
            cbxProductos.addItem(rs.getString("nombre"));
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
            
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFinalizarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        btnEliminarSuborden = new javax.swing.JButton();
        cbxProductos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnNuevaSuborden = new javax.swing.JButton();
        btnListaSubordenes = new javax.swing.JButton();
        btnMenuprincipal = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubordenes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 520));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 520));

        btnFinalizarVenta.setBackground(new java.awt.Color(0, 209, 59));
        btnFinalizarVenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnFinalizarVenta.setText("Finalizar venta");
        btnFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVentaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 30)); // NOI18N
        jLabel1.setText("Registro de venta");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setText("Total:");

        lblTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(33, 172, 25), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 51), new java.awt.Color(0, 204, 51)));

        jLabel3.setBackground(new java.awt.Color(242, 94, 68));
        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel3.setText("Numero de mesa:");

        txtNumeroMesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153), 2));

        btnEliminarSuborden.setText("Eliminar");
        btnEliminarSuborden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSubordenActionPerformed(evt);
            }
        });

        cbxProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductosActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(242, 94, 68));
        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");

        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153), 2));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnNuevaSuborden.setText("Nuevo Plato");
        btnNuevaSuborden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSubordenActionPerformed(evt);
            }
        });

        btnListaSubordenes.setText("Lista de platos");
        btnListaSubordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaSubordenesActionPerformed(evt);
            }
        });

        btnMenuprincipal.setBackground(new java.awt.Color(220, 220, 220));
        btnMenuprincipal.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnMenuprincipal.setText("Menu Principal");
        btnMenuprincipal.setBorder(new javax.swing.border.MatteBorder(null));
        btnMenuprincipal.setPreferredSize(new java.awt.Dimension(150, 50));
        btnMenuprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuprincipalActionPerformed(evt);
            }
        });

        btnTickets.setText("Tickets");
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });

        tblSubordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Plato", "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        // ✅ Add a TableModelListener after initializing the table
        tblSubordenes.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    int fila = e.getFirstRow();
                    int columna = e.getColumn();

                    if (columna == 3) { // ✅ Corrected column index for "Cantidad"
                        actualizarSubtotal(fila);
                        actualizarTotal();
                    }
                }
            }
        });
        jScrollPane1.setViewportView(tblSubordenes);
        if (tblSubordenes.getColumnModel().getColumnCount() > 0) {
            tblSubordenes.getColumnModel().getColumn(0).setMinWidth(0);
            tblSubordenes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSubordenes.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSubordenes.getColumnModel().getColumn(1).setPreferredWidth(2);
            tblSubordenes.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListaSubordenes, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(btnNuevaSuborden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarSuborden, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMenuprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarVenta))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenuprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevaSuborden)
                            .addComponent(btnEliminarSuborden))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListaSubordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTickets))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
                    DefaultTableModel modeloTabla = (DefaultTableModel) tblSubordenes.getModel();
                    

    String productoSeleccionado = (String) cbxProductos.getSelectedItem();
    String cantidadStr = txtCantidad.getText();

    if (productoSeleccionado != null && !cantidadStr.trim().isEmpty()) {
        try {
            int cantidad = Integer.parseInt(cantidadStr);

            // Obtener precio del producto desde la base de datos
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tacarbon_db", "root", "m1o3r5a7");
            String sql = "SELECT  id, precio FROM productos WHERE nombre = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, productoSeleccionado);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                Long productoId = rs.getLong("id");  // Obtener el ID del producto
                double precio = rs.getDouble("precio");
                double total = cantidad * precio;


            // Agregar a la tabla con el ID antes de currentSuborden
            modeloTabla.addRow(new Object[]{productoId, currentSuborden, productoSeleccionado, cantidad, precio, total});
            
            // Force table update
            modeloTabla.fireTableDataChanged();
            
            // Scroll to last row
            int lastRow = modeloTabla.getRowCount() - 1;
            if (lastRow >= 0) {
            tblSubordenes.scrollRectToVisible(tblSubordenes.getCellRect(lastRow, 0, true));
            }


            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad válida.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un producto e ingrese la cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        // (Opcional) Si tienes un total, actualizarlo
        actualizarTotal();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnNuevaSubordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSubordenActionPerformed
        // TODO add your handling code here:
        // Get the highest suborden number before adding a new one
    if (!subordenes.isEmpty()) {
        currentSuborden = Collections.max(subordenes); // Find the highest suborden
    }
    currentSuborden++; //Increment before adding
    subordenes.add(currentSuborden);
    JOptionPane.showMessageDialog(this, "Plato " + currentSuborden + " Creado");
    }//GEN-LAST:event_btnNuevaSubordenActionPerformed

private void actualizarSubtotal(int fila) {
    DefaultTableModel modelo = (DefaultTableModel) tblSubordenes.getModel();
    
    try {
        // ✅ Validate Cantidad is a valid number
        Object cantidadObj = modelo.getValueAt(fila, 3);
        if (cantidadObj == null || cantidadObj.toString().trim().isEmpty()) {
            return; // Do nothing if Cantidad is empty
        }
        int cantidad = Integer.parseInt(cantidadObj.toString());

        // ✅ Get Precio (either from the table or from the database)
        double precio;
        Object precioObj = modelo.getValueAt(fila, 4);
        
        if (precioObj == null) {
            // If precio is missing, fetch it from the database
            String productoSeleccionado = modelo.getValueAt(fila, 2).toString(); // Product name
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tacarbon_db", "root", "m1o3r5a7");
            String sql = "SELECT precio FROM productos WHERE nombre = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, productoSeleccionado);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                precio = rs.getDouble("precio");
                modelo.setValueAt(precio, fila, 4); // ✅ Save precio in table
            } else {
                throw new Exception("Precio no encontrado para " + productoSeleccionado);
            }

            conn.close();
        } else {
            precio = Double.parseDouble(precioObj.toString());
        }

        // ✅ Calculate new subtotal
        double nuevoSubtotal = cantidad * precio;
        modelo.setValueAt(nuevoSubtotal, fila, 5); // ✅ Update subtotal column (5)

        actualizarTotal(); // ✅ Update total
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingrese un número válido en Cantidad", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar subtotal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void actualizarTotal() {
    DefaultTableModel model = (DefaultTableModel) tblSubordenes.getModel();
    double total = 0.0;

    // Suponiendo que la columna del precio total está en el índice 5
    for (int i = 0; i < model.getRowCount(); i++) {
        total += Double.parseDouble(model.getValueAt(i, 5).toString());
    }

    lblTotal.setText(String.format("$ %.2f", total)); // Muestra el total en un JLabel
}

    private void btnEliminarSubordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSubordenActionPerformed
        // TODO add your handling code here:
            // Obtener el modelo de la tabla
    DefaultTableModel model = (DefaultTableModel) tblSubordenes.getModel();
    
    // Obtener la fila seleccionada
    int selectedRow = tblSubordenes.getSelectedRow();
    
    // Verificar si se ha seleccionado una fila
    if (selectedRow != -1) {
        // Eliminar la fila seleccionada
        model.removeRow(selectedRow);
        
        // (Opcional) Si tienes un total, actualizarlo
        actualizarTotal();
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona algo para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarSubordenActionPerformed

    private void btnListaSubordenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaSubordenesActionPerformed
        // TODO add your handling code here:
        
            if (subordenes.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay platos creados.");
        return;
    }

    // Convert list to array for JOptionPane
    String[] opciones = subordenes.stream().map(s -> "Plato " + s).toArray(String[]::new);

    // Show selection dialog
    String seleccion = (String) JOptionPane.showInputDialog(this, 
            "Seleccione un plato:", "Lista de platos",
            JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

    // If a Suborden was selected, switch to it
    if (seleccion != null) {
        currentSuborden = Integer.parseInt(seleccion.split(" ")[1]);
        JOptionPane.showMessageDialog(this, "Ahora estás en " + seleccion);
    }
    }//GEN-LAST:event_btnListaSubordenesActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
     // implement all handling code here
    try {
        // Step 1: Get table number
        int numeroMesa = Integer.parseInt(txtNumeroMesa.getText());

        // Step 2: Get order details from JTable
        DefaultTableModel model = (DefaultTableModel) tblSubordenes.getModel();
        List<Map<String, Object>> detallesVenta = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            Map<String, Object> detalle = new HashMap<>();
            detalle.put("producto", Map.of("id", Integer.valueOf(model.getValueAt(i, 0).toString()))); // Product ID
            detalle.put("cantidad", Integer.valueOf(model.getValueAt(i, 3).toString()));  // Quantity
            detalle.put("precio", Double.valueOf(model.getValueAt(i, 4).toString()));  // Price (added this line)
            detallesVenta.add(detalle);
        }

        if (detallesVenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay productos en la venta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Step 3: Create JSON request body
        Map<String, Object> ventaData = new HashMap<>();
        ventaData.put("numeroMesa", numeroMesa);
        ventaData.put("detalles", detallesVenta); // Sending details including price

        Gson gson = new Gson();
        String jsonInputString = gson.toJson(ventaData);

        // Step 4: Send HTTP POST request
        URL url = new URL("http://localhost:8080/api/ventas");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);

        try (OutputStream os = conn.getOutputStream()) {
            byte[] input = jsonInputString.getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Step 5: Read the response
        int responseCode = conn.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_CREATED) {
            JOptionPane.showMessageDialog(this, "Venta registrada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Clear UI after successful sale
            model.setRowCount(0);
            txtNumeroMesa.setText("");
            txtCantidad.setText("");
            lblTotal.setText("$0.00"); // This will be recalculated by the backend
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar venta: " + responseCode, "Error", JOptionPane.ERROR_MESSAGE);
        }

        conn.disconnect();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al finalizar la venta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Clear the txtNumeroMesa text field
        txtNumeroMesa.setText("");
    
        // Clear the txtCantidad text field
        txtCantidad.setText("");
        
        //clear lblTotal
        lblTotal.setText("$0.00");

            // Reset scrollbar to the top
        if (tblSubordenes.getRowCount() > 0) {
        tblSubordenes.scrollRectToVisible(tblSubordenes.getCellRect(0, 0, true));
        }
        
        // Clear the table (tblSubordenes)
        DefaultTableModel model = (DefaultTableModel) tblSubordenes.getModel();
        model.setRowCount(0);  // Remove all rows from the table
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnMenuprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuprincipalActionPerformed
        // TODO add your handling code here:
        // Dispose of the current form (RegistroProductoForm)
        this.dispose();
    
        // Open the MainPOSWindow
        MainPOSWindow mainWindow = new MainPOSWindow();
        mainWindow.setVisible(true);  // Show the MainPOSWindow
    }//GEN-LAST:event_btnMenuprincipalActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
        new TicketViewer().setVisible(true);
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void cbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductosActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVentaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarSuborden;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnListaSubordenes;
    private javax.swing.JButton btnMenuprincipal;
    private javax.swing.JButton btnNuevaSuborden;
    private javax.swing.JButton btnTickets;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblSubordenes;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNumeroMesa;
    // End of variables declaration//GEN-END:variables
}


