/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;

/**
 *
 * @author moral
 */
public class TicketViewer extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private File ticketsFolder;
    /**
     * Creates new form TicketViewer
     */
    public TicketViewer() {
        initComponents();
        tableModel = (DefaultTableModel) ticketTable.getModel();
        // Carpeta donde se guardan los tickets
        ticketsFolder = new File("tickets");
        // Load ticket files into JList
        loadTicketData();
    }
    
        // Load ticket data from PDF files
    private void loadTicketData() {
        tableModel.setRowCount(0); // Clear table before loading new data

        File[] files = ticketsFolder.listFiles((dir, name) -> name.endsWith(".pdf"));
        if (files != null) {
            for (File file : files) {
                String fileName = file.getName();
                String date = getCreationDate(file);
                String[] extractedData = extractTicketInfo(file);

                if (extractedData != null) {
                    tableModel.addRow(new Object[]{date, extractedData[0], extractedData[1], fileName});
                }
            }
        }
    }
    
    
    // Extract ID Venta & Numero de Mesa from PDF
    private String[] extractTicketInfo(File file) {
        try (PDDocument document = PDDocument.load(file)) {
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(document);

            // Extract ID Venta and Mesa using regex or simple string search
            String idVenta = text.contains("ID Venta:") ? text.split("ID Venta:")[1].split("\n")[0].trim() : "N/A";
            String numeroMesa = text.contains("Numero de mesa:") ? text.split("Numero de mesa:")[1].split("\n")[0].trim() : "N/A";

            return new String[]{idVenta, numeroMesa};
        } catch (IOException e) {
            return null; // If error reading PDF, return null
        }
    }
    
        // Get file creation date
    private String getCreationDate(File file) {
    try (PDDocument document = PDDocument.load(file)) {
        PDFTextStripper stripper = new PDFTextStripper();
        String text = stripper.getText(document);

        // Look for "Fecha: " and extract the date
        String fechaLinea = text.contains("Fecha:") ? text.split("Fecha:")[1].split("\n")[0].trim() : "Unknown";

        // Extract only the date part (before 'T')
        return fechaLinea.contains("T") ? fechaLinea.split("T")[0] : fechaLinea;

    } catch (IOException e) {
        return "Unknown";
    }
    }
    
        // Open selected PDF
    private void openSelectedTicket() {
        int selectedRow = ticketTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un ticket primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
                String fileName = (String) tableModel.getValueAt(selectedRow, 3);
        File ticketFile = new File(ticketsFolder, fileName);

        if (ticketFile.exists()) {
            try {
                Desktop.getDesktop().open(ticketFile);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al abrir el ticket.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        btnOpenTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Punto de venta Tacarbon - Visor de Tickets");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Venta", "Mesa", "Archivo"
            }
        ));
        ticketTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ticketTable);

        btnOpenTicket.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnOpenTicket.setText("Abrir Ticket");
        btnOpenTicket.setPreferredSize(new java.awt.Dimension(150, 50));
        btnOpenTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnOpenTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnOpenTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticketTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketTableMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_ticketTableMouseClicked

    private void btnOpenTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTicketActionPerformed
        // TODO add your handling code here:
        openSelectedTicket(); // Call the method directly
    }//GEN-LAST:event_btnOpenTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables
}
